name: madsci_sim_lab

# * Common configuration
x-madsci-service: &madsci-service
  image: ghcr.io/ad-sdl/madsci:dev_ryan
  environment:
    - USER_ID=${USER_ID:-1000}
    - GROUP_ID=${GROUP_ID:-1000}
  network_mode: host
  volumes:
    - ./madsci_sim_lab:/home/madsci/madsci_sim_lab
    - ./.madsci:/home/madsci/.madsci
  restart: unless-stopped
  working_dir: /home/madsci/madsci_sim_lab

services:
  # *Databases (note: these are non-persistent, add volumes for persistence)
  mongodb:
    container_name: mongodb
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: redis:7.4
    restart: unless-stopped
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=madsci
      - POSTGRES_PASSWORD=madsci
      - POSTGRES_DB=resources
    ports:
      - 5432:5432

  # *Managers
  event_manager:
    <<: *madsci-service
    container_name: event_manager
    command: python -m madsci.event_manager.event_server
    depends_on:
      - mongodb

  lab_manager:
    <<: *madsci-service
    container_name: lab_manager
    image: ghcr.io/ad-sdl/madsci_dashboard:dev_ryan
    command: python -m madsci.squid.lab_server
    depends_on:
      - event_manager

  experiment_manager:
    <<: *madsci-service
    container_name: experiment_manager
    command: python -m madsci.experiment_manager.experiment_server
    depends_on:
      - mongodb
      - lab_manager

  resource_manager:
    <<: *madsci-service
    container_name: resource_manager
    command: python -m madsci.resource_manager.resource_server
    depends_on:
      - postgres
      - event_manager

  data_manager:
    <<: *madsci-service
    container_name: data_manager
    command: python -m madsci.data_manager.data_server
    depends_on:
      - mongodb
      - event_manager

  workcell_manager:
    <<: *madsci-service
    container_name: workcell_manager
    command: python -m madsci.workcell_manager.workcell_server --cold_start_delay 0
    depends_on:
      - redis
      - mongodb
      - resource_manager
      - event_manager
      - postgres