git submodule add https://github.com/AD-SDL/MADSci.git MADSci_Core
git submodule add https://github.com/AD-SDL/MADSci_Examples.git MADSci_Examples
git submodule add https://github.com/AD-SDL/a4s_sealer_module.git MADSci_Modules/a4s_sealer_module
git submodule add https://github.com/AD-SDL/barty_module.git MADSci_Modules/barty_module
git submodule add https://github.com/AD-SDL/big_kahuna_module.git MADSci_Modules/big_kahuna_module
git submodule add https://github.com/AD-SDL/brooks_xpeel_module.git MADSci_Modules/brooks_xpeel_module
git submodule add https://github.com/AD-SDL/camera_module.git MADSci_Modules/camera_module
git submodule add https://github.com/AD-SDL/hidex_module.git MADSci_Modules/hidex_module
git submodule add https://github.com/AD-SDL/hudson_platecrane_module.git MADSci_Modules/hudson_platecrane_module
git submodule add https://github.com/AD-SDL/hudson_solo_module.git MADSci_Modules/hudson_solo_module
git submodule add https://github.com/AD-SDL/inheco_incubator_module.git MADSci_Modules/inheco_incubator_module
git submodule add https://github.com/AD-SDL/labjack_module.git MADSci_Modules/labjack_module
git submodule add https://github.com/AD-SDL/liconic_module.git MADSci_Modules/liconic_module
git submodule add https://github.com/AD-SDL/metrohm_m101_module.git MADSci_Modules/metrohm_m101_module
git submodule add https://github.com/AD-SDL/object_detection_module.git MADSci_Modules/object_detection_module
git submodule add https://github.com/AD-SDL/ot2_module.git MADSci_Modules/ot2_module
git submodule add https://github.com/AD-SDL/pal_module.git MADSci_Modules/pal_module
git submodule add https://github.com/AD-SDL/pe_icp_module.git MADSci_Modules/pe_icp_module
git submodule add https://github.com/AD-SDL/pf400_module.git MADSci_Modules/pf400_module
git submodule add https://github.com/AD-SDL/sciclops_module.git MADSci_Modules/sciclops_module
git submodule add https://github.com/AD-SDL/transfer_meta_module.git MADSci_Modules/transfer_meta_module
git submodule add https://github.com/AD-SDL/ur_module.git MADSci_Modules/ur_module
git submodule add https://github.com/AD-SDL/vention_rail_module.git MADSci_Modules/vention_rail_module
git submodule add https://github.com/AD-SDL/zigbee_module.git MADSci_Modules/zigbee_module