name: Scaling MVP Test Workflow
metadata:
  author: Simlab
  info: Simple test workflow for parallel environment verification
  version: '1.0'

parameters: []

steps:
  - name: Open Thermocycler
    node: thermocycler
    action: open

  - name: Close Thermocycler
    node: thermocycler
    action: close
